# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://help.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
# commenting out pkg for now because they cause build failures without subsequent manual intervention
# due to go mod tidy needing to be run on all dependents
#  - package-ecosystem: "gomod" # See documentation for possible values
#    directory: "/pkg" # Location of package manifests
#    schedule:
#      interval: "weekly"
  - package-ecosystem: "gomod" # See documentation for possible values
    directory: "/admin-reports" # Location of package manifests
    schedule:
      interval: "weekly"
    ignore:
      # ignore all Kubernetes minor updates beyond cluster version
      - dependency-name: "k8s.io/api"
        update-types: ["version-update:semver-minor"]
      - dependency-name: "k8s.io/apimachinery"
        update-types: ["version-update:semver-minor"]
      - dependency-name: "k8s.io/client-go"
        update-types: ["version-update:semver-minor"]
  - package-ecosystem: "gomod" # See documentation for possible values
    directory: "/distutil" # Location of package manifests
    schedule:
      interval: "weekly"
  - package-ecosystem: "gomod" # See documentation for possible values
    directory: "/instructional-area-gen" # Location of package manifests
    schedule:
      interval: "weekly"
  - package-ecosystem: "gomod" # See documentation for possible values
    directory: "/listdistricts" # Location of package manifests
    schedule:
      interval: "weekly"
  - package-ecosystem: "gomod" # See documentation for possible values
    directory: "/nwea-mock-server" # Location of package manifests
    schedule:
      interval: "weekly"
  - package-ecosystem: "gomod" # See documentation for possible values
    directory: "/pubsub" # Location of package manifests
    schedule:
      interval: "weekly"
  - package-ecosystem: "gomod" # See documentation for possible values
    directory: "/pull-demographics" # Location of package manifests
    schedule:
      interval: "weekly"
  - package-ecosystem: "gomod" # See documentation for possible values
    directory: "/pull-test-results" # Location of package manifests
    schedule:
      interval: "weekly"
  - package-ecosystem: "gomod" # See documentation for possible values
    directory: "reports" # Location of package manifests
    schedule:
      interval: "weekly"
  - package-ecosystem: "gomod" # See documentation for possible values
    directory: "roster" # Location of package manifests
    schedule:
      interval: "weekly"
  - package-ecosystem: "gomod" # See documentation for possible values
    directory: "signer" # Location of package manifests
    schedule:
      interval: "weekly"
  - package-ecosystem: "gomod" # See documentation for possible values
    directory: "yearend" # Location of package manifests
    schedule:
      interval: "weekly"
### Docker
  - package-ecosystem: "docker" # See documentation for possible values
    directory: "admin-reports" # Location of package manifests
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker" # See documentation for possible values
    directory: "pubsub" # Location of package manifests
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker" # See documentation for possible values
    directory: "pull-demographics" # Location of package manifests
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker" # See documentation for possible values
    directory: "pull-test-results" # Location of package manifests
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker" # See documentation for possible values
    directory: "reports" # Location of package manifests
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker" # See documentation for possible values
    directory: "roster" # Location of package manifests
    schedule:
      interval: "weekly"
