name: golangci-lint
on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
env:
  GOPRIVATE: "github.com/Khan"
  GOFLAGS: "-trimpath"
  GO_VERSION: 1.18
jobs:
  golangci:
    name: Linter
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          # stable: 'false' # Keep this line to be able to use rc and beta version of Go (ex: 1.18.0-rc1).
          go-version: ${{ env.GO_VERSION }}
      - uses: actions/checkout@v2
      - name: lint
        uses: golangci/golangci-lint-action@v3.1.0
        with:
          version: latest
          # skip cache because of flaky behaviors
          skip-build-cache: true
          skip-pkg-cache: true
          args: --timeout 5m --issues-exit-code=0
          # only-new-issues: true #show only new issues if it's a pull request. options working-directory and only-new-issues are incompatible