name: Test
on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master
env:
  GOPRIVATE: "github.com/Khan"
  GOFLAGS: "-trimpath"
  GO_VERSION: 1.18
jobs:
  test:
#    runs-on: [self-hosted, linux, x64]
    runs-on: ubuntu-latest
    timeout-minutes: 40
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ env.GO_VERSION }}
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Test
      run: |-
        echo "starting go tests without race"
        go test ./... -timeout 5m -v -trimpath