name: Test
on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
env:
  GOPRIVATE: "github.com/Khan"
  GOFLAGS: "-trimpath"
  GO_VERSION: 1.18
jobs:
  test:
#    runs-on: [self-hosted, linux, x64]
    runs-on: ubuntu-latest
    timeout-minutes: 40
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ env.GO_VERSION }}
    - name: Setup Gcloud
      uses: 'google-github-actions/setup-gcloud@v0'
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        install_components: 'beta,cloud-datastore-emulator'
        # export_default_credentials: true
        # Old bad way without workload identity federation:
        # service_account_key: ${{ secrets.GCP_GCR_SA_KEY }}
        # service_account_email: ${{ secrets.GCP_GCR_SA_EMAIL }}
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Test
      run: |-
        echo "starting go tests without race"
        go test ./... -timeout 5m -v -trimpath